name: Build Docker Images
on: 
  pull_request:
    branches:
    - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image for user service
        run: docker build ./user-services --tag user_services_image:$(date +%s)